### ISSUE TITLE
Sakura Taisen 2 - Incorrect sound effects

### ISSUE THREAD

**Issue by MattoBii** [MiSTer-devel/Saturn_MiSTer#172]
Sound effects for all the different timer types in Sakura Wars 2 are incorrect. Most notably the steam sound effect for when the green timer's meter fills halfway is heavily corrupted. Footage attached is taken from the Sakura Wars 2 Japanese demo disc for ease of replication, but has been confirmed to occur in the full game the same way. Footage taken from the MiSTer core (20240323 build) and original hardware, in that order, for comparison.

https://github.com/MiSTer-devel/Saturn_MiSTer/assets/164713977/d7a352ec-7cfe-4963-b249-0e5c03cda630

https://github.com/MiSTer-devel/Saturn_MiSTer/assets/164713977/dd16adf9-fd8b-4d38-bf5b-852c1cebcd36

**Comment by JaeOfMordor** [comment]
the sfx issue you noted is now fixed in the latest unstable-nightlies build, feel free to test and close this when possible.

**Comment by MattoBii** [comment]
Having just tested this with the latest unstable build, the steam sound effect is no longer corrupted, but the timer sound effects remain incorrect.

**Comment by Kuba-J** [comment]
Fixed with today test core 20240403

https://github.com/MiSTer-devel/Saturn_MiSTer/commit/bd90d3afce6b150526f737e3229758f4c576a2b0

**Comment by real-amano** [comment]
@MattoBii is this fixed with the latest revision?

**Comment by MattoBii** [comment]
Having tested it again just now on the latest version, the timer sound is still incorrect.

**Comment by Zet-sensei** [comment]
PLFO have been fixed and sound interpolation have been added on 2024-08-10 version.

Please retest if the timer sound is correct now.

**Comment by JaeOfMordor** [comment]
almost perfect, did a side by side comparison with a headphone from each source playing at the same time.

the only one that was off was the double lips system long counter. which can be heard starting at 2:07

so the algorithm is nearly correct, maybe just one tweak to go.

**Comment by Zet-sensei** [comment]
Should be fixed with commit https://github.com/MiSTer-devel/Saturn_MiSTer/commit/58b4c280d52359988bb3893e6b977778690cdc12

**Comment by real-amano** [comment]
@MattoBii is it fixed for you now? Can You close the bug?

**Comment by MattoBii** [comment]
Sounds like it's all fixed! Closing the bug.
