### ISSUE TITLE
Grandia flickering Still Present on MiSTer Pi Setup

### ISSUE THREAD

**Issue by jhdgghost** [MiSTer-devel/Saturn_MiSTer#355]
Hello,

I am reopening [Issue #210](https://github.com/MiSTer-devel/Saturn_MiSTer/issues/210) as the problem has not been resolved.

As I previously mentioned in the issue, I am experiencing the same flickering issue with my new MiSTer Pi setup. The flickering is clearly visible, and the intro behaves exactly as shown in the video 73793200542__6A518E90-0DDD-4BB5-A4C1-8FA7AC1A559D.MOV from JaeOfMordor. The SD card I am using is the one provided in the Turbo MiSTer Pi Setup (Batch 2).

Apologies if reopening the issue is not the best approach, but I was unsure if my previous comment had been noticed. Hopefully, now the issue can be replicated with a MiSTer Pi setup for further investigation.

**Comment by Kuba-J** [comment]
From my observations and user testing , it seems that the game works well 100% on dualsdram. After moving the ram-h to the other sdram the problem stopped. As for the performance with one sdram is a lottery , for some it works better or worse. Zakk did tests with overcloking ddr3 memory and the flickering problems disappeared (I don't know if completely). I think there is a reason why the description says:
"Note: Dual SDRAM modules is recommended for better compatibility."

**Comment by jhdgghost** [comment]
It seems like single RAM core is improving and getting closer to dual RAM performance over time. Additionally, single RAM setups are more common. The main issue, as you mentioned, is that this seems to be a lottery—some single RAM setups experience the issue while others do not. However, if the issue occurs on Mister Pi, that could help with replication of the issue and potentially lead to a fix. Maybe the problem is the speed of the SDRAM being faster in certain setups.

**Comment by srg320** [comment]
> It seems like single RAM core is improving and getting closer to dual RAM performance over time.

I have reached the end of the possibilities to improve the RAM-H speed for a single sdram build.

> However, if the issue occurs on Mister Pi, that could help with replication of the issue and potentially lead to a fix.

Mister Pi does not use the original FPGA board. This board has a different track layout and possibly different timings. Since the core requires high memory frequencies for correct operation, there may be different stability results with a different track layout. I am focusing only on the original board from Terasic. 

> Maybe the problem is the speed of the SDRAM being faster in certain setups.

According to the video of the issue, the instability probably occurs in the operation of the onboard ddr3 memory.

**Comment by jhdgghost** [comment]
Thanks for the feedback, srg320. So, for this game in Single RAM, is the best solution Zakk's approach of overclocking DDR3 memory? I could try that to see if it also fixes the issue on my end, but I'm not sure how easy it would be for me, as I'm still new to FPGA.

Can I test the overclocking through software, or does it have to be done at the hardware level? I'm hesitant to modify the MiSTer at the hardware level, but if it's possible through software, I’d be willing to try Zakk's solution and report back.

**Comment by srg320** [comment]
I don't know how to overclock ddr3. It is better to ask this question to the author of the post about overclocking.

**Comment by saebaryo** [comment]
Hello,

I am also experiencing the same flickering issue.

- DE10-Nano
- Single SDRAM (v3.0) : This issue also occurs with v2.5 and v2.9, so it may not be related.
- 512GB SD Card 

![Image](https://github.com/user-attachments/assets/87691eff-98e0-48eb-9699-24bf32b25027)

- Saturn_unstable_20250215
- The issue was not present in Saturn_unstable_20240409, but it started occurring in later versions.


Here is a video showing the issue:

https://github.com/user-attachments/assets/0753a899-3fe0-4774-8368-e3802bd31d13



The following settings produce a stable display without issues:

- Overclocking DDR3 memory to 950000 KHz (Default: 800000 KHz)
- https://github.com/coolbho3k/MiSTer-Overclock-Scripts
- Hardware Menu-> Timing : Fast

https://github.com/user-attachments/assets/1c659f41-51ab-47e8-9abd-2f32a2e976c5

**Comment by srg320** [comment]
The main problem why I can't fix this issue is that I can't reproduce it on my hardware. Maybe reducing the frequency of DDR3 memory will help to reproduce the issue .

**Comment by srg320** [comment]
Try these builds.

[Saturn.zip](https://github.com/user-attachments/files/18922430/Saturn.zip)

**Comment by JaeOfMordor** [comment]
all of these offer some improvement when fast timing is enabled.
saturn_1 was probably the best. with the least amount of de-synchronizing between the floor and the wall.
3 would still flicker a little. as well as the wall/floor 
de-synchronizing.

**Comment by jhdgghost** [comment]
Confirm Saturn_1 is the best still i get some flickering in the intro flying sequence where the flickering is very evident but much reduced compared to version 0,2 and 3.

**Comment by srg320** [comment]
Try these builds.

[Saturn_1.zip](https://github.com/user-attachments/files/18930178/Saturn_1.zip)

**Comment by JaeOfMordor** [comment]
i prefer the scrolling of the wall/floor sprites with saturn_1_1, the differences between builds are subtle.
it does slightly improve the de-synchronization and removes 99% of the flickering when fast timing is enabled, but repeating running around indoors can cause it anyway.

saturn_1_0 seems to be the same as previous builds, 1_2 and 1_3 seem to have worse de-synchronization than 1_1

**Comment by jhdgghost** [comment]
Agree 1_1 look better than previous 1 still some flickering is still present but is much reduced.

**Comment by srg320** [comment]
For some unknown reason, ddr3 works slower on some boards. It would be interesting to compare the chip markings on your and my boards. On my board, the problem occurs only when I reduce the ddr3 frequency from 800MHz to 650MHz.

In single sdram build ddr3 memory is used more intensively and the speed is not enough for the core to work accurately. So don't expect perfect results on your boards. I will integrate the changes from build 1_1 to the FAST option. These changes may return issues #95, #100, #110, #111. So you should use the option only in exceptional cases.

**Comment by biro1214** [comment]
Menu itens, dont work in the Dungeons. Last unstable core single and dual ram.

**Comment by Kuba-J** [comment]
> ![Image](https://github.com/user-attachments/assets/d5050dc1-dc0a-4576-ac2c-d46c2782aedd) Menu itens, dont work in the Dungeons. Last unstable core single and dual ram.

confirmed , when go to menu with items , game stop to respond for any button on the controller

to reproduce 

save: [Grandia (Japan).zip](https://github.com/user-attachments/files/18996329/Grandia.Japan.zip)

pick first one , go into any battle on the field

pick form menu: 

![Image](https://github.com/user-attachments/assets/f300b40d-cf94-4545-935f-879c52f41eac)

**Comment by biro1214** [comment]
Fixed on last unstable core. Thanks.

**Comment by Kuba-J** [comment]
> Fixed on last unstable core. Thanks.

I still have a problem with menu navigation , even if it works for a while it stops responding to the buttons

**Comment by Kuba-J** [comment]
> > Fixed on last unstable core. Thanks.
> 
> There is a problem. The issue has not been fixed yet. The issue is not related to the flickering issue, so it's better to report it as a separate issue.

issue opened https://github.com/MiSTer-devel/Saturn_MiSTer/issues/372
